#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

echo "Running linting pre-commit hook..."

npm run lint

if [ $? -ne 0 ]; then
  echo "Damn linting failed! Commit aborted."
  exit 1
fi

echo "pre-commit passed, continuing with commit."
exit 0
